### ISSUE TITLE
Division by zero error - Trail plot

### ISSUE THREAD

**Issue by gjr80** [gjr80/weewx-polarwindplot#44]
Suspect it's due to a lack of data as error disappeared on next archive period. Simulator that had been silent for > 24 hours. Following log refers:
```
Jan 20 08:07:53 bullseye33 weewx[510] INFO __main__: Starting up weewx version 4.5.1
Jan 20 08:07:53 bullseye33 weewx[510] INFO weewx.engine: Clock error is -5.93 seconds (positive is fast)
Jan 20 08:07:53 bullseye33 weewx[510] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jan 20 08:07:53 bullseye33 weewx[510] INFO weewx.manager: Starting backfill of daily summaries
Jan 20 08:07:53 bullseye33 weewx[510] INFO weewx.manager: Daily summaries up to date
Jan 20 08:07:53 bullseye33 weewx[510] INFO weewx.engine: Starting main packet loop.
Jan 20 08:08:15 bullseye33 weewx[510] INFO weewx.manager: Added record 2022-01-20 08:08:00 AEST (1642630080) to database 'weewx.sdb'
Jan 20 08:08:15 bullseye33 weewx[510] INFO weewx.manager: Added record 2022-01-20 08:08:00 AEST (1642630080) to daily summary in 'weewx.sdb'
Jan 20 08:08:16 bullseye33 weewx[510] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.52 seconds
Jan 20 08:08:18 bullseye33 weewx[510] INFO weewx.imagegenerator: Generated 60 images for report SeasonsReport in 1.91 seconds
Jan 20 08:08:18 bullseye33 weewx[510] INFO weewx.reportengine: Copied 5 files to /home/weewx/public_html
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.polarwindplot.PolarWindPlotGenerator'
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****  float division by zero
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 196, in run
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****      obj.start()
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 281, in start
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****      self.run()
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 169, in run
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****      self.genPlots(self.gen_ts)
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 288, in genPlots
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****      image = plot_obj.render(title)
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 1983, in render
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****      self.render_plot()
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/user/polarwindplot.py", line 2070, in render_plot
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****      scale = plot_radius / self.max_vector_radius
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****  ZeroDivisionError: float division by zero
Jan 20 08:08:18 bullseye33 weewx[510] ERROR weewx.reportengine:         ****  Generator terminated
```

**Comment by gjr80** [comment]
Issue is not due to a lack of data but rather a lack of non-zero wind speed data. Fixed at commit d855f8b4716aa3561b4c6e6d7ecd587132083ecb.
